// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA77D3twtPvR91WeIRrlMaUWPp6ZcEEqxU',
    appId: '1:1009694371406:android:f1b8f71c487e8c2c6edd1f',
    messagingSenderId: '1009694371406',
    projectId: 'talkflip',
    databaseURL: '',
    storageBucket: 'talkflip.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJLRtNflGAFx8U1Y7mB5jKkK8mFMiThpw',
    appId: '1:1009694371406:ios:194244c2eb498e666edd1f',
    messagingSenderId: '1009694371406',
    projectId: 'talkflip',
    databaseURL: '',
    storageBucket: 'talkflip.firebasestorage.app',
    iosBundleId: 'com.example.talkflip',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJLRtNflGAFx8U1Y7mB5jKkK8mFMiThpw',
    appId: '1:1009694371406:ios:194244c2eb498e666edd1f',
    messagingSenderId: '1009694371406',
    projectId: 'talkflip',
    databaseURL: '',
    storageBucket: 'talkflip.firebasestorage.app',
    iosBundleId: 'com.example.talkflip',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA77D3twtPvR91WeIRrlMaUWPp6ZcEEqxU',
    appId: '1:1009694371406:web:c5d3e8f9a2b1c4d7e8f9a',
    messagingSenderId: '1009694371406',
    projectId: 'talkflip',
    authDomain: 'talkflip.firebaseapp.com',
    databaseURL: '',
    storageBucket: 'talkflip.firebasestorage.app',
  );
}
